function test_doublepoints_analysis()
	
	close all
	
	load ~/rsyncfolder/data/WNV/FullSimulationNewRuleNewAdvect/DoublePoints.mat
	
	Ctot = [];
	leg={};
	ctr = 0;
	for Ng = Ngvec;
		ctr=ctr+1;
		s = eval(['results.Ng',int2str(Ng)]);
		figure
		Ccontourviz(s.xg,s.yg,s.C(:,:,end),s.params,s.Tvec(end));
		Ctot(:,ctr) = CO2sum(s.C);
		leg{end+1} = ['N = ', int2str(Ng)];
	end
	
	figure
	plot(s.Tvec,Ctot,'LineWidth',2)
	set(gca,'FontSize',24)
	set(gcf,'PaperSize',[8,6])  
	set(gcf,'PaperPosition',[0,0,8,6])
	xlabel('Nondiml time')
	ylabel('Total nondiml CO_2')
	legend(leg,'Location','SouthEast')


end %function

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
function Ctot = CO2sum(C);
	
	% THE INPUT ARGUMENT IS A 3D MATRIX COMPOSED OF A TIME SEQUENCE OF CO2 VALUES ON A 2D GRID. X,Y,T ARE THE VARIABLES ASSOCIATED WITH THE 1ST, 2ND, AND 3RD DIMENSIONS RESPECTIVELY. THE OUTPUT ARGUMENT IS A TIMESERIES OF THE TOTAL CO2 IN THE DOMAIN OVER TIME.
	
	Ctot = [];
	for k = 1:size(C,3);
		Ctot(k) = sum(sum(C(:,:,k)));
	end
end %function
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
function Ccontourviz(xg,yg,C,p,t);

	contour(xg,yg,C)
	axis([0,p.L,0,p.L])
	colormap(cool)
	colorbar
	set(gca,'FontSize',24)
	set(gcf,'PaperSize',[8,6])  
	set(gcf,'PaperPosition',[0,0,8,6])
	title(['N = ', int2str(p.Ng),', nondiml time = ',num2str(t)])

end %function
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
function [C_interp,maxdif,maxdif_scaled]=CO2interpolate(xg,yg,C,xg_fine,yg_fine,C_fine);
	
	% INTERPOLATE FROM COARSE GRID TO FINE GRID AND COMPARE RESULTS.  THIS FUNCTION TAKES 6 MATRIX ARGUMENTS. THE FIRST TWO ARE THE X AND Y POINTS OF A 2D COARSE GRID GENERATED BY MESH GRID, AND A CO2 CONCENTRATION MATRIX OF THE SAME SIZE. THE LAST THREE ARE THE SAME FOR A FINE GRID.


	maxdif = [];
	maxdif_scaled = [];
	C_interp = interp2(xg,yg,C,xg_fine,yg_fine,'*linear');
	difvec = C_fine - C_interp;
	maxdif(k) = max(max(abs(difvec)));
	maxdif_scaled(k) = maxdif(k)/max(max(C_fine));
		
end %function
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%







