function N = GrowVisuals(C,savename,titulo,s)
% Saves a .bmp of the full carbon dioxide spread generated by GrowCO2


minC = min(min(C)); maxC = max(max(C));
s.dCm = 0.000040; s.dCM = 0.004000;

contour(s.X,s.Y,C,minC:((maxC-minC)/20):maxC);
title(titulo);
axis equal, axis([s.x0 s.xf s.y0 s.yf]), colorbar
colormap(cool)
hold on
contour(s.X,s.Y,C,[s.dCm,s.dCM],':k','LineWidth',2);
hold off
N = gcf;
saveas(N,['C:/Users/User/Documents/Dropbox/WNVproject/MATLAB/New Version/Images/GrowCO2/',savename,'.bmp'])

% ,[s.dCm,s.dCM],':k','LineWidth',2