%=========================================================================%
% JUNK
%=========================================================================%

%-------------------------------------------------------------------------%
% unit switching

switch unit
    case 'cm'
        [C,tn,dt,S,Sx,Sy,K,windx,windy,h,X,Y,mx,my,S_max,S_min,b0,bsat,...
            kappa,Cdirmin,Cdirmax,mdt,mt0,Vdirmin,Vdirmax,wind_thresh,...
            wind_sat,wind_kappa,wind_mode,cross_switch,windweight,...
            gradweight,host_radius,x0,xf,y0,yf,Gsat,Gthresh,dc,...
            crosswind_duration,frames,Nx,D] = Variable_cm(chickencount,...
            littlechicken,windtype,mosqcount,windsense);
    case 'dm'
        [C,tn,dt,S,Sx,Sy,K,windx,windy,h,X,Y,mx,my,S_max,S_min,b0,bsat,...
            kappa,Cdirmin,Cdirmax,mdt,mt0,Vdirmin,Vdirmax,wind_thresh,...
            wind_sat,wind_kappa,wind_mode,cross_switch,windweight,...
            gradweight,host_radius,x0,xf,y0,yf,Gsat,Gthresh,dc,...
            crosswind_duration,frames,Nx,D] = Variable_dm(chickencount,...
            littlechicken,windtype,mosqcount,windsense);
    case 'm'
        [C,tn,dt,S,Sx,Sy,K,windx,windy,h,X,Y,mx,my,S_max,S_min,b0,bsat,...
            kappa,Cdirmin,Cdirmax,mdt,mt0,Vdirmin,Vdirmax,wind_thresh,...
            wind_sat,wind_kappa,wind_mode,cross_switch,windweight,...
            gradweight,host_radius,x0,xf,y0,yf,Gsat,Gthresh,dc,...
            crosswind_duration,frames,Nx,D] = Variable_m(chickencount,...
            littlechicken,windtype,mosqcount,windsense);
    case 'ft'
        [C,tn,dt,S,Sx,Sy,K,windx,windy,h,X,Y,mx,my,S_max,S_min,b0,bsat,...
            kappa,Cdirmin,Cdirmax,mdt,mt0,Vdirmin,Vdirmax,wind_thresh,...
            wind_sat,wind_kappa,wind_mode,cross_switch,windweight,...
            gradweight,host_radius,x0,xf,y0,yf,Gsat,Gthresh,dc,...
            crosswind_duration,frames,Nx,D] = Variable_ft(chickencount,...
            littlechicken,windtype,mosqcount,windsense);
    case '10ft'
        [C,tn,dt,S,Sx,Sy,K,windx,windy,h,X,Y,mx,my,S_max,S_min,b0,bsat,...
            kappa,Cdirmin,Cdirmax,mdt,mt0,Vdirmin,Vdirmax,wind_thresh,...
            wind_sat,wind_kappa,wind_mode,cross_switch,windweight,...
            gradweight,host_radius,x0,xf,y0,yf,Gsat,Gthresh,dc,...
            crosswind_duration,frames,Nx,D] = ...
            Variable_10ft(chickencount,littlechicken,windtype,mosqcount,...
            windsense);
end

format long
Nx_h_D_dt = [Nx h D dt];
format short
%-------------------------------------------------------------------------%

